### ISSUE TITLE
Confidential or private

### ISSUE THREAD

**Issue by JackMatthams** [nhsuk/nhsuk-service-manual-community-backlog#202]
## What
- Add "confidential" and "private" entries into the A to Z, suggesting to use "confidential" and not "private". 

## Why
- "Confidential" is better than "private" - whilst they both mean similar things, "confidential" does not imply a cost to the service, whereas "private" could be interpreted in this way. 

- This came from the NHSE pharmacy campaign: @NaoPattem  and the NHSE pharmacy team found "confidential consultation room" had a clearer and more appropriate meaning than "private consultation room", with the latter implying a potential cost. They currently use "private" on their website, which is where this issue was found.

**Comment by sarawilcox** [comment]
The proposal to the February Style Council meeting was to add the following 2 entries to the A to Z of NHS health writing.  

**Confidential** 

We use both "confidential" and "private". We use "confidential" when talking about privacy in a consultation or conversation. This is because some people think "private" means there's a cost.  

**Private** 

We use both "confidential" and "private". We use "confidential" when talking about privacy in a consultation or conversation. This is because some people think "private" means there's a cost. 

But at the Style Council meeting, some people thought it better to explain what confidential means as we aren’t sure that people understand the word. For example, we could say something like "a quiet conversation that no one else can hear". With “private”, we thought it worth a note to remind people that it can be misunderstood.  

We decided to put the issue on hold pending further research/testing.

**Comment by sarawilcox** [comment]
Putting this back into To Do column.

**Comment by sarawilcox** [comment]
I've just asked on the NHS.UK content channel if anyone has any further user insight around this.

**Comment by sarawilcox** [comment]
No one has shown and interest in this issue on the NHS.UK or public Slack channels. Close it down.
