### ISSUE TITLE
Pronunciation - improve accessible pronunciation help for screen readers

### ISSUE THREAD

**Issue by SiRose** [nhsuk/nhsuk-service-manual-community-backlog#298]
## What
Create a way for screen readers to pronounce words correctly and accessibly, by breaking up words into meaningful chunks. 

## Why
Screen readers pronounce regular words that they recognise, but have little reference point for how to pronounce words that are:
- unusual, like condition names
- long, with multiple syllables
- two words combined into one, as a concept, like coronavirus
- products that aren't genuine words, like medicine names and brands

The Bridgewater Place accessibility lab - due to move to the new Leeds Hub - had a range of devices, including several with assistive technology like screen readers.

I used some on our own [NHS.UK coronavirus content](https://www.nhs.uk/conditions/coronavirus-covid-19/) a while ago and it became clear that 'coronavirus' was a problem for screen readers to pronounce.

If the condition was 2 words they'd be pronounced as 'corona' followed by 'virus'. But the phrase has become the single-word concept 'coronavirus'. Screen readers have little reference point to pronounce coronavirus as 1 word.

Many screen readers operate at a fast speed and with an American accent: 'coronavirus' is pronounced more like 'cornaverous'. It sounds like 'carnivorous', but we're not talking about a dinosaur here.

It struck me at the time and continues to since that we're doing screen readers a disservice if we allow words to be pronounced strangely, as that is likely to be misleading and distracting. It could impair recognition, understanding and safe self-care.

Coronavirus is incredibly important. Understanding it and so many other non-standard words should be for everyone.

## Anything else
I discussed this issue at the time with @mcheung-nhs.  He mentioned that there could be a way to handle this, with back end code that could help to break up the syllables, for screen readers to pronounce such words in more accessible chunks. This might need to be editable in Wagtail, for content designers to specify pronunciations.

Mike pointed me towards a GOV.UK blog for [how to create content that works well with screen readers](https://accessibility.blog.gov.uk/2017/02/08/advice-for-creating-content-that-works-well-with-screen-readers/). It outlines the challenges and how what might work for one type of user can affect others adversely.

I believe we should investigate how much of a problem screen reader pronunciation is, for words like coronavirus and so many others, to help word pronunciation be more meaningful, so that our content remains accessible for everyone. 

I wonder if we know enough about that and if NHS.UK has tested screen reader pronunciation specifically. Research like this might find a simple solution that could help users across NHS.UK and lead to others learning from us.

**Comment by sarawilcox** [comment]
Hi @SiRose, thanks for raising this. @mcheung-nhs and I talked with Alistair Duggin about it. The consensus was that:
- most screen readers users listen at high speed and are used to how things sound on their particular set up - it might sound weird to us but not necessarily to them
- even if we were to come up with a solution to make things pronounce better on our website, people would run into the same issue on other websites 
- screen reader users can go back to anything they don't understand and "interrogate" it further, e.g. 1 letter at a time
- fixing it for some users could make it worse for others (for example, for braille users)

(You noted some of these issues above.)

Because of this, we don't think we should be making any changes at the moment. We'll close the ticket, if you're OK with that.

The other point that Alistair made is whether we should do anything that helps all users pronounce or understand difficult words better. 
- We've wondered in the past (but not made a decision) about whether [human papillomavirus](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/48) is better spelt papilloma-virus. 
- Also the meds team was experimenting with helping users to pronounce the names of their medicines so that they would feel more confident talking about them with health professionals.

These may be worth exploring further.
