### ISSUE TITLE
Diagnosis - and prognosis

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-community-backlog#75]
It will help content designers if we can clarify whether we use "diagnosed" or "diagnosis". Or do we say "you have" or "your doctor has told you you have ..."? 

Please talk to the 111 team, as they raised this as an issue. They have seen users struggle with the terms.

Is it different in different contexts, e.g. in cancer?

There is a Jira ticket for this issue: SS-395

**Comment by sarawilcox** [comment]
We received a query via Twitter about the words diagnosis and prognosis - so I've added prognosis too. We were also sent a reference to this article: https://medium.com/wehearthealthliteracy/just-say-no-to-nosis-bdf5b9e44988

**Comment by sarawilcox** [comment]
Yes, according to an NHS.UK Slack conversation: 
111 avoid "diagnosis". Saying instead "has a doctor told you that you have X?" In UR we found people were unsure about 'diagnosis'. Particularly those with English as a second language

We've tended to "outlook" instead of prognosis historically on NHS.uk. Though this was only based on assumption of prognosis not being well understood.

**Comment by sarawilcox** [comment]
Slack conversation: We've always used 'diagnosis'. 'diagnosed', 'diagnose' etc. in the A-Z primarily because we've usually had a diagnosis page. I think it would be difficult to avoid using it in all contexts (there are lot). As Mark says we use 'outlook' instead of 'prognosis' as it's plainer (mainly for cancer topics). There are a few older news pages that use prognosis. Personally, I'd say don't use prognosis but diagnosis is trickier in terms of the Health A-Z.

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel to see how much interest there is in this issue now. Can we close it?

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. I'm closing the issue.
