### ISSUE TITLE
Pain scale

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-community-backlog#98]

**Comment by sarawilcox** [comment]
We have some research that suggests that we should limit the pain scale to care cards and perhaps get rid of it. For now, we're postponing work on this pending more work on the care cards.

**Comment by cjforms** [comment]
Clarification on the research: 
We've now met clinicians Caron Walker and Enid Povey, and content designer Kimberley Darke who were all involved in co-designing the "pain scale component".
They made it clear that the "pain scale component" was designed, and is intended, solely for use within a care card.  
We have a revised report on the research that incorporates new information from their views on the component.
We agreed that any future work on the "pain scale component" needs to be done as part of an overall package of considering care cards. I suggest that this ticket is combined with one on care cards, if available. 
In addition, Kimberley suggested (and I agree) that the name "pain scale component" is misleading and recommended renaming it to something that reflects its purpose, which is helping someone who is considering contacting NHS urgent care because of pain to understand whether that pain is severe enough to decided to continue with the contact. 

It is not, and never was, intended as a general tool for assessing pain.

**Comment by cjforms** [comment]
The complications of the traditional scales for assessing pain are accurately discussed in this comic strip:
https://existentialcomics.com/comic/290

**Comment by sarawilcox** [comment]
To be considered alongside any further work on [Care cards](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/80). 
In the meantime, I'm putting this back into the Proposed column. No action is being taken on it for now.

**Comment by sarawilcox** [comment]
I'm putting out a call on the NHS.UK Slack content channel. Can we close this issue now?

**Comment by cjforms** [comment]
My recommendation is that you close the issue and also that you decide NOT to build or use a pain scale.

**Comment by cjforms** [comment]
I didn't see anything on the NHS Digital Service Manual slack.

**Comment by sarawilcox** [comment]
No, I put it in the NHS.UK Slack instance @cjforms, not the public Slack channel. I hoped you'd get a notification from GitHub, which you did.

**Comment by sarawilcox** [comment]
No recent interest in this issue on NHS.UK or service manual public Slack channels. @Kimb0D, are you OK with us closing this issue?

**Comment by sarawilcox** [comment]
Here's an example of describing pain in terms of what you can and can't do.

<img width="584" alt="Screenshot 2022-12-02 at 14 30 57" src="https://user-images.githubusercontent.com/45792959/205321501-096776ba-f4bb-4b06-99b3-e88a63b2dcaf.png">

**Comment by cjforms** [comment]
I'd support 'not doing' 

The specific example fails to address many of the issues around pain. For example, it's confused the 'effect on daily life' aspect of pain with the severity. It's entirely possible to have severe pain that comes and goes - as in "if I lie in this exact position then the pain is mild, but I cannot change position without it being excruciating". 

In this example, I'd greatly prefer it for the authors to describe what they mean by severe pain in this context and forget about the extra descriptions of mild and moderate pain which are just extra words that add nothing to the 'see the GP' instruction.

**Comment by sarawilcox** [comment]
Thanks @cjforms. One of our teams is looking at how people describe pain. I've shared this ticket with them so they'll see your comment.

**Comment by cjforms** [comment]
I've still got the massive book on pain assessment on the bookcase behind me - tell them to give me a shout if they want me to look stuff up in it. ("Handbook of pain assessment" editors Dennis C Turk and Ronald Melzack. Mine is the 3rd edition, 2011).
